pull_request_rules:
- name: automatically merge scala-steward's PRs
  actions:
    merge:
      method: squash
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success=Build and Test (ubuntu-latest, 2.12.13, adopt@1.11)
  - status-success=Build and Test (ubuntu-latest, 2.12.13, adopt@1.15)
  - status-success=Build and Test (ubuntu-latest, 2.13.4, adopt@1.11)
  - status-success=Build and Test (ubuntu-latest, 2.13.4, adopt@1.15)
